# Generated by Django 3.2 on 2022-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primernombre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundonombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primerapellido', models.CharField(blank=True, max_length=50, null=True)),
                ('segundoapellido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipodocumento', models.CharField(blank=True, max_length=50, null=True)),
                ('numerodocumento', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
    ]
