# Generated by Django 3.2 on 2022-03-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipoactivo',
            },
        ),
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('serial', models.CharField(blank=True, max_length=250, null=True)),
                ('numerointerno', models.CharField(blank=True, max_length=250, null=True)),
                ('peso', models.CharField(blank=True, max_length=250, null=True)),
                ('alto', models.CharField(blank=True, max_length=250, null=True)),
                ('ancho', models.CharField(blank=True, max_length=250, null=True)),
                ('largo', models.CharField(blank=True, max_length=250, null=True)),
                ('valorcompra', models.CharField(blank=True, max_length=250, null=True)),
                ('fechacompra', models.CharField(blank=True, max_length=250, null=True)),
                ('fechabaja', models.CharField(blank=True, max_length=250, null=True)),
                ('estadoactual', models.CharField(blank=True, choices=[('activo', 'activo'), ('dado de baja', 'dado de baja'), ('en reparación', 'en reparación'), ('disponible', 'disponible'), ('asignado', 'asignado')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tipoactivo')),
            ],
            options={
                'db_table': 'activo',
            },
        ),
    ]
